# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Capture the Vagrant command
  v_arg = ARGV[0]

  # Give vm definition a handle
  config.vm.define "mate_base"

  # Build upon base box from Vagrant repository
  config.vm.box = "ubuntu/bionic64"

  # Uncomment public network and populate with your bridged IP
  # config.vm.network "public_network", ip: "< YOUR IP >"
  # config.vm.network "private_network", type: "dhcp"

  # Mount shared folders required for initialization
  config.vm.synced_folder "shared", "/home/vagrant/shared"
  
  # We don't want to insert a vagrant key into the box
  config.ssh.insert_key = false

  config.vm.provider "virtualbox" do |vb|
    # GUI
    vb.gui = false
    # Customize the amount of memory on the VM:
    vb.memory = "2048"
    # Support working when on 3DS VPN (Required for adapter provisioning on VPN)
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    # Enable multi-core
    vb.cpus = 4
    vb.customize ["modifyvm", :id, "--ioapic", "on"]
    vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
  end

  config.vm.provision "shell", path: "./scripts/provision.sh"
     
  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "provision_mate.yml"
    ansible.provisioning_path = "/home/vagrant/ansible"
    # True by default. Set explicitly as this is intended
    ansible.install = true  
    ansible.install_mode = "pip"
    ansible.version = "2.6.7"
    ansible.groups = {
      "matei3" => ["mate"],
      "all:children" => ["mate"]
    }
    ansible.host_vars = {
      "remote_user" => "vagrant"
    }
  end 

  config.vm.provision "shell", path: "purge.sh"

end
