---
 - name: Install common base packages
   become: True
   apt:
     name: "{{ packages }}"
   vars:
     packages:
      - feh
      - tmux
      - ranger
      - git
      - xclip
      - vim
      - curl
      - wget


 - name: Install google-chrome
   become: True
   apt:
     deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb


 - name: Set vim as default editor
   lineinfile:
     path: '/home/vagrant/.bashrc'
     insertafter: EOF
     line: "{{ item }}"
   with_items:
     - 'export VISUAL=vim'
     - 'export EDITOR="$VISUAL"'
