#
# Configure mate for compatibility with i3
#
---
 - name: Copy dconf settings file to local system
   copy:
     src: dconf.org.mate.settings
     dest: '/tmp/dconf.org.mate.settings'


 - name: Apply dconf settings for panels
   shell: dconf load /org/mate/ < /tmp/dconf.org.mate.settings
