#
# Configure mate for compatibility with i3
#
---
 - name: Switch Window Manager to i3
   shell: dconf write /org/mate/desktop/session/required-components/windowmanager "'i3'"


 - name: Disable desktop icons
   shell: dconf write /org/mate/desktop/background/show-desktop-icons "false"
