#
# Configure mate for compatibility with i3
#
---
 - name: Switch Window Manager to i3
   shell: dconf write /org/mate/desktop/session/required-components/windowmanager "'i3'"


   # By default file-manager and other components are added that we don't want
 - name: Set Mate Desktop session required-components-list
   shell: dconf write /org/mate/desktop/session/required-components-list "['window-manager', 'panel']"

   # If we don't do this we get the desktop as an i3 window
 - name: Disable desktop icons
   shell: dconf write /org/mate/desktop/background/show-desktop-icons "false"


   # Favor using i3 wallpaper w/ feh
 - name: Disable Mate background
   shell: dconf write /org/mate/desktop/background/draw-background "false"
