# Configure i3
---
 - name: Create i3 config directory
   file:
     path: /home/vagrant/.config/i3
     state: directory
     owner: vagrant
     group: vagrant


 - name: Apply i3 settings
   copy:
     src: i3-config
     dest: '/home/vagrant/.config/i3/config'