#
# Reference: https://github.com/Airblader/xcb-util-xrm/issues/75
#
---
 - name: Clone xcb-util-xrm package
   git:
     repo: 'https://github.com/Airblader/xcb-util-xrm.git'
     dest: '/home/vagrant/p/lib/Airblader/xcb-util-xrm'


 - name: Update git submodule
   shell: git submodule update --init
   args:
     chdir: '/home/vagrant/p/lib/Airblader/xcb-util-xrm'

 - name: Autogen xcb-util-xrm
   shell: ./autogen.sh
   args:
     chdir: '/home/vagrant/p/lib/Airblader/xcb-util-xrm'


 - name: Build xcb-util-xrm
   gather_facts: True
   make:
     chdir: '/home/vagrant/p/lib/Airblader/xcb-util-xrm'
     params:
      - NUM_THREADS: "{{ ansible_processor_vcpus }}"


 - name: Install xcb-util-xrm
   become: True
   make:
     chdir: '/home/vagrant/p/lib/Airblader/xcb-util-xrm'
     target: install
