---
 - name: Install prerequisites
   become: True
   apt:
     name: build-essential
     update_cache: True

     
 - name: Fetch nodejs setup script
   become: True
   get_url:
     url: https://deb.nodesource.com/setup_{{ nodejs_version }}.x
     dest: /tmp/node_setup.sh


 - name: Execute nodejs setup
   become: True
   shell: /tmp/node_setup.sh


 - name: Remove nodejs setup
   become: True
   file:
     path: /tmp/node_setup.sh
     state: absent


 - name: Install nodejs
   become: True
   apt:
     name: nodejs