---
 - name: Ensure required dependencies are installed
   become: True
   apt:
     name: "{{ item }}"
     update_cache: True
   with_items:
    - vim
    - git


 - name: Create .vim directory for plugins
   file:
     path: /home/vagrant/.vim/bundle
     owner: vagrant
     group: vagrant
     state: directory


 - name: Clone and install Vundle plugin manager for Vim
   git:
     repo: https://github.com/VundleVim/Vundle.vim.git
     dest: /home/vagrant/.vim/bundle/Vundle.vim


 - name: Install vimrc
   copy:
     src: .vimrc
     dest: /home/vagrant/.vimrc


   # https://stackoverflow.com/questions/33672491/how-to-use-ansible-to-provision-vim-vundle-plugin
 - name: Install vim plugins (Disable visual interface)
   shell: vim -E -s -c "source /home/vagrant/.vimrc" -c PluginInstall -c qa
   ignore_errors: True
