---
 - hosts: all
   roles:
    - { role: 'ansible-role-python' }
    - { role: 'configure_vim' }
    - { role: 'install_docker' }
    - { role: 'install_nodejs' }
    - { role: 'install_sublime' }
    - { role: 'ansible-role-vscode' }
