---
 - name: Install python3
   become: True
   apt:
     name: "{{ item }}" 
     update_cache: yes
   with_items:
    - python3.7
    - python3-pip


 - name: Install pip packages
   pip:
     name: "{{ item }}"
     executable: pip3
   with_items:
    - virtualenv
    - setuptools
    - pipenv