---
 - name: Install python3
   become: True
   apt:
     name: python3 
     update_cache: yes


 - name: Install pip packages
   pip:
     name: "{{ item }}"
   with_items:
    - virtualenv
    - setuptools
    - pipenv