---
 - name: Install python3
   become: True
   apt:
     name: "{{ item }}" 
     update_cache: yes
   with_items:
    - python3.7
    - python3-pip


 - name: Install pip packages
   pip:
     name: "{{ item }}"
     executable: pip3
   with_items:
    - virtualenv
    - setuptools
    - pipenv


 - name: Set python3.7 as default for both python and python3
   become: True
   shell: update-alternatives --install {{ item }} 10
   with_items:
    - '/usr/bin/python3 python3 /usr/bin/python3.7'
    - '/usr/bin/python python /usr/bin/python3.7'